spring:
  datasource:
    url: jdbc:mysql://192.168.9.212:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hhp123
#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
