server:
  port: 8130

spring:
  profiles:
    active: dev #环境配置
  application:
    name: service-oss #服务名
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 # nacos服务地址

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    keyId: LTAI5tFbF2dgsxmhzhM9KHRr
    keySecret: YLX6S9CLfLeAWCan3j3pSTJNugKPu5
    bucketName: hhp002